### ISSUE TITLE
Icon: cuisine=friture

### ISSUE THREAD

**Issue by jbelien** [jbelien/openstreetmap-carto-be#3]
I think it would be nice to replace the default icon for `amenity=fast_food` when `cuisine=friture`.

Something like this : https://www.iconfinder.com/icons/189409/food_french_fries_vegetable_icon

**Could someone create such an icon ?**

**Comment by jbelien** [comment]
Poke @gplv2 !

**Comment by gplv2** [comment]
Ouch.  I'll do my best, probably when I'm done translating all GRB tags, which is advancing well.

**Comment by jbelien** [comment]
Ping @nobohan 😋

**Comment by timcouwelier** [comment]
[icon in action](https://matrix.to/#/!SqvNXrBsvdGHYRyota:matrix.org/$1522933541662686toepW:matrix.org)

Not sure where his 'final icon' is at, there were struggles with the mayo color, not sure if resolved by now, or if the mayo has just gone bad.

**Comment by jbelien** [comment]
For reference :
![frietkot](https://user-images.githubusercontent.com/1150563/38747010-bc48c432-3f49-11e8-88b2-efc296488a47.png)

I think the icon is too big and too far from the style of the usual icons.
But I like the direction this takes 💪
