### ISSUE TITLE
Osm2pgsql failed due to ERROR: Could not open style file '/home/ant/src/openstreetmap-carto-be/openstreetmap-carto.style': No such file or directories

### ISSUE THREAD

**Issue by AtomStark** [jbelien/openstreetmap-carto-be#8]
Hi Jonathan,

I will say right away that I just started to understand with osm.
Followed by your instructions, it is understandable and convenient.
But there is one problem:
At the Loading data step, when you run the command:

`osm2pgsql --create --slim -C 2500 --number-processes 2 -S ~ / src / openstreetmap-carto-be / openstreetmap-carto.style --multi-geometry ~ / data / belgium-latest.osm.pbf`

An error occurs:

`Osm2pgsql failed due to ERROR: Could not open style file '/home/ant/src/openstreetmap-carto-be/openstreetmap-carto.style': No such file or directories`

I read the instructions first, but I did not understand how to fix it.
Sorry for bothering you. Thank you in advance.

**Comment by jbelien** [comment]
Hello @AtomStark ,
I'll have a look and come back to you :)

Which documentation did you use ?
If you used [Installation (Ubuntu 16.04)](https://github.com/jbelien/openstreetmap-carto-be/wiki/Installation-(Ubuntu-16.04)), I suggest you switch to latest version : [Installation (Ubuntu 17.04)](https://github.com/jbelien/openstreetmap-carto-be/wiki/Installation-(Ubuntu-17.04)).

**Comment by AtomStark** [comment]
I used Installation (Ubuntu 16.04)

**Comment by jbelien** [comment]
Hey @AtomStark ,

I just run the process described in "Installation (Ubuntu 16.04)" and it works just fine.
Please check you didn't skip a step and that all the paths are good :)

Especially this one `/home/ant/src/openstreetmap-carto-be/openstreetmap-carto.style` ! It will depend where you cloned this repo.
